### ISSUE TITLE
Several issues with lab, missing fetch dependency

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/react-redux-assessment#6]
1. The lab instructions specify that the catsReducer should only have one method, the FETCH_CATS method. I needed to add another method, LOADING_CATS.
2.Test is highly opinionated on names of props
3. Fetch needed to be imported in the cats_action file

**Comment by dkStephanos** [comment]
these are solid issues, but pretty sure you meant to submit this on the preceding lab.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the tests, solution and readme in the previous redux thunk lab and believe your issues have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
